
services:


  mysql: # 服务名称
    image: mysql:8.0 # 或其它mysql版本
    container_name: mysql_8.0 # 容器名称
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # root用户密码
      - TZ=Asia/Shanghai # 设置容器时区 我这里通过下面挂载方式同步的宿主机时区和时间了,这里忽略
    volumes:
      - /Users/oneday/Downloads/var/data/mysql/log:/var/log/mysql # 映射日志目录，宿主机:容器
      - /Users/oneday/Downloads/var/data/mysql/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - /Users/oneday/Downloads/var/data/mysql/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
      - /etc/localtime:/etc/localtime:ro # 让容器的时钟与宿主机时钟同步，避免时间的问题，ro是read only的意思，就是只读。
    ports:
      - 3306:3306 # 指定宿主机端口与容器端口映射关系，宿主机:容器
    restart: always # 容器随docker启动自启


  redis:
    image: redis:latest
    container_name: redis_latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /Users/oneday/Downloads/var/data/redis/data:/data
      - /Users/oneday/Downloads/var/data/redis/redis.conf:/etc/redis/redis.conf
      - /Users/oneday/Downloads/var/data/redis/logs:/logs
    #配置文件启动
    command: redis-server /etc/redis/redis.conf


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper_latest
    ports:
      - '2181:2181'
    environment:
      # 匿名登录--必须开启
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /Users/oneday/Downloads/var/data/kafka/zookeeper:/bitnami/zookeeper
  # 该镜像具体配置参考 https://github.com/bitnami/bitnami-docker-kafka/blob/master/README.md


  kafka:
    image: 'bitnami/kafka:2.8.0'
    container_name: kafka_2.8
    ports:
      - '9092:9092'
      # - '9999:9999'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # 客户端访问地址，更换成自己的
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # 允许使用PLAINTEXT协议(镜像中默认为关闭,需要手动开启)
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 开启自动创建 topic 功能便于测试
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # 全局消息过期时间 6 小时(测试时可以设置短一点)
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
      # 开启JMX监控
      - JMX_PORT=9999
    volumes:
      - /Users/oneday/Downloads/var/data/kafka/kafka:/bitnami/kafka
    depends_on:
      - zookeeper
  # Web 管理界面 另外也可以用exporter+prometheus+grafana的方式来监控 https://github.com/danielqsj/kafka_exporter
  # kafka_manager:
  #   image: 'hlebalbau/kafka-manager:latest'
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     ZK_HOSTS: "zookeeper:2181"
  #     APPLICATION_SECRET: letmein
  #   depends_on:
  #     - zookeeper
  #     - kafka
