
server:
  port: 49003

spring:
  application:
    name: frauddetection-event
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/frauddetection?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: frauddetection
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    topic:
      name: topic-frauddetection-event
    replication:
      factor: 3
    partition:
      number: 16
    consumer:
      group-id: frauddetection-event-group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      level:
        concurrency: 5
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

logging:
  file:
    path: /Users/oneday/Downloads/var/data/logs/frauddetection-event-sdk
  level:
    root: DEBUG
